#ifndef __HTTPREQUEST_H__
#define __HTTPREQUEST_H__

#define HTTP_METHOD_GET 0
#define HTTP_METHOD_POST 1
#define HTTP_METHOD_PUT 2
#define HTTP_METHOD_DELETE 3
#define HTTP_METHOD_CONNECT 4
#define HTTP_METHOD_OPTIONS 5
#define HTTP_METHOD_HEAD 6
#define HTTP_METHOD_TRACE 7

#endif
